### ISSUE TITLE
Some sample text files contain zero newlines or more than one newline

### ISSUE THREAD

**Issue by lemzwerg** [googlei18n/nototools#110]
`wc -l *_udhr.txt | sort` in directory `sample_texts` gives interesting information... Assuming that all sample text files provide a single line of text, there are the following files that violate this assumption.

No newline at the end:

    cs-Latn_uhdr.txt
    mn-Mong_uhdr.txt
    sl-Latn_uhdr.txt

More than a single line:

    krl-Latn_uhdr.txt
    qug-Latn_uhdr.txt

I guess this should be fixed, which is rather trivial.

**Comment by lemzwerg** [comment]
Thanks for the quick fix!

**Comment by dougfelt** [comment]
Sure.  Nice to have an easy bugfix now and again.
