### ISSUE TITLE
Korean text sample in mixed script?

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/nototools#120]
I would like to modify the Korean text sample (taken from Omniglot.com) to display mixed script either in addition to or in place of the current hangeul-only sample, to display Noto Sans CJK KR's inclusion of hanja:
모든 人間은 태어날 때부터 自由로우며 그 尊嚴과 權利에 있어 同等하다. 人間은 天賦的으로 理性과 良心을 賦輿받았으며 서로 兄弟愛의 精神으로 行動하여야 한다.

**Comment by jungshik** [comment]
I have an even better sample text in mind. To fully demonstrate the capability of Noto Sans (CJK) KR, I'm going to use '훈민정음언해' with old Hangul and tone marks.
