### ISSUE TITLE
Include more of the unicode UDHR samples in the sample text.

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#15]
Include more of the unicode UDHR samples in the sample text.

The general problem is that we do not have a collection of samples that adequately exercises the fonts in all the languages we intend them to support.  Getting more sample text is a small step in that direction.

Moved from googlei18n/noto-fonts#328

**Comment by dougfelt** [comment]
The general problem of getting more sample data is a bit different from this.  We do have code now to use the UDHR samples where possible.
