### ISSUE TITLE
Make sure each Noto script/family with a font has at least one language assigned to it and a sample

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#16]
Moved from googlei18n/noto-fonts#82

**Comment by jamesgk** [comment]
cc @roozbehp @marchbox @xiangyexiao

**Comment by dougfelt** [comment]
Everything has a sample.  Not everything has actual text, several are just collections of characters.  In several cases this is probably the best we can do (hieroglyphics, emoji).  We need to vet the text, which means we need to get it from a source we trust or have a native speaker vouch for the quality and 'inoffensiveness' of the text, and this is difficult.  We use the UDHR text on the unicode site for the text we have, in most places.
