### ISSUE TITLE
Include things that are not cmap'd in fontdiff

### ISSUE THREAD

**Issue by rsheeter** [googlei18n/nototools#161]
If I understand correctly, fontdiff appears to only compare what is cmap'd. 

It would be helpful to compare things that are accesible by open type feature. That is, render all the stuff you can reach by GPOS/GSUB rules as well. See discussion on #158.

This would help Google Fonts with things like broken ligatures in new versions of fonts :)

**Comment by davelab6** [comment]
This would require a method that parses the OTL and returns all the unicode strings needed to show all the glyphs with `hb-view`. This is beyond my skills...

**Comment by jamesgk** [comment]
This was already on my todo list for fontdiff, I can look into it.

**Comment by rsheeter** [comment]
Awesome, thanks James. Will pay Guinness for fix!

We have a couple of revs of Merriweather that might be helpful for testing :)

**Comment by davelab6** [comment]
:dart:

**Comment by dougfelt** [comment]
@jamesgk, it would be helpful if the code to generate all the strings necessary to generate all the glyphs produced by the GSUB table were separate from fontdiff, or conveniently callable from nototools.  There are a number of uses for those strings.

**Comment by davelab6** [comment]
@behdad is there anything that parses a font and returns all the unicode strings needed to show all the glyphs, already?

**Comment by behdad** [comment]
> @behdad is there anything that parses a font and returns all the unicode strings needed to show all the glyphs, already?

No.  But we're very close when otlLib.unbuild stuff is done.

**Comment by davelab6** [comment]
@behdad okay cool - hope you can wrangle a convenient method to return such a list :)
