### ISSUE TITLE
Rebrand DroidSansMono as NotoMono

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#2]
There are public requests on the mailing list about Noto Monospace. We should 
rebrand DroidSansMono to NotoMono: 
https://groups.google.com/forum/#!topic/noto-font/7UGfWAScfOk

The changes are trivial and can be easily done by someone on the Noto team.

Moved from googlei18n/noto-fonts#333

**Comment by jamesgk** [comment]
cc @roozbehp @jamesgk @dougfelt

**Comment by marekjez86** [comment]
@xiangyexiao : one day please teach me what it takes to re-brand a Noto font

**Comment by xiangyexiao** [comment]
@jungshik, any reason not to rebrand Droid Mono to Noto?

**Comment by jungshik** [comment]
Not at all. I thought we had decided to do that, but perhaps we haven't, yet. 
@xiangyexiao

**Comment by dougfelt** [comment]
I'm wondering why this bug is in nototools?  There's no Droid-branded fonts
in the noto repositories.  Is it in roboto?

**Comment by roozbehp** [comment]
Droid Mono is in the Android tree, and it would be nice if it moves to (and get rebranded as) Noto.

**Comment by xiangyexiao** [comment]
I cannot find Noto Sans Monospace at https://github.com/googlei18n/noto-fonts/tree/master/unhinted

Where are the Droid Mono fonts (except of Android)?

**Comment by roozbehp** [comment]
I don't know any other location other than the Android tree, where it's at frameworks/base/data/fonts.

**Comment by xiangyexiao** [comment]
filed a new bug in the noto-fonts github repo and close this bug.

https://github.com/googlei18n/noto-fonts/issues/592
