### ISSUE TITLE
Windows Link Seems to be Broken

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#20]
This is the website's Windows download link.

Moved from googlei18n/noto-fonts#338

**Comment by marekjez86** [comment]
on https://www.google.com/get/noto/help/install/ Windows download seems to work
@jamesgk : looks like it's fixed, but I might be missing something

**Comment by dougfelt** [comment]
Works for me too.  The website has changed a few times since June 9th, so I expect this was fixed.
