### ISSUE TITLE
unicode_data.py to use unicodedata2

### ISSUE THREAD

**Issue by twardoch** [googlei18n/nototools#205]
I see that [unicode_data.py](https://github.com/googlei18n/nototools/blob/master/nototools/unicode_data.py) is doing: 
```
import unicodedata  # Python's internal library
```

It would be more efficient to do: 
```
try: 
  import unicodedata2 as unicodedata
except ImportError: 
  import unicodedata
```

`unicodedata2` is a C++ Python 2.7-compatible "unicodedata" replacement (Apache2-licensed) which is currently at Unicode 8.0. So the "inefficient" lookups done in pure Python could be sped up if that library was used:
https://github.com/mikekap/unicodedata2
https://pypi.python.org/pypi/unicodedata2

**Comment by anthrotype** [comment]
Just to clarify, the built-in `unicodedata` module is written in C so it is not "inefficient" nor "pure Python" as you suggest:
https://hg.python.org/cpython/file/v2.7.11/Modules/unicodedata.c#l1111

The one included in 2.7.11 is outdated (Unicode 5.2). Python 3.5 has Unicode 8.0.0.

unicodedata2 is a backport to Python2 of the Python3 unicodedata module, so I'd also recommend it if one is stuck with Python2.

**Comment by anthrotype** [comment]
Please ignore my comments above. I just realised Adam wasn't referring to the inefficiency of the built-in `unicodedata`, but to the fact that one has to parse the huge text files to get unicode data which is up to date.

**Comment by dougfelt** [comment]
Sure.  Note however that unicodedata is only used to return character names.  The whole point of unicode_data.py is to use prerelease unicode data files that aren't in any official library.  So the need to parse text files will never go away.

**Comment by twardoch** [comment]
I know that unicode_data.py exposes more properties and uses the bleeding-edge data files. I'll add that even though Python 3.5 may have its built-in unicodedata compatible with Unicode 8.0.0, when Unicode 9.0.0 gets released, the built-in unicodedata module will get the update with certainly some delay, while it's very likely that the author of unicodedata2 will publish it quickly (since unicodedata2 seems like it's "maintained"). 

I've used the 
```py
try: 
  import unicodedata2 as unicodedata
except ImportError: 
  import unicodedata
```
myself in a number of projects, and it seems like a fine compromise for more general-purpose efficient character lookup — if you're on Py3, you may not care about installing unicodedata2 since the builtin unicodedata is good enough, but on Py2, unicodedata2 is a much better choice over the ancient unicodedata. So to me, it's kind of like a "standard construct" now, pretty much for ANY use whenever I want to use the basic fast Unicode name or simple property lookup. 

But noto's unicode_data is nice because it exposes more, and uses the prerelease files. So for "bleeding-edge uses" or if I need more Unicode properties exposes, it's great.
