### ISSUE TITLE
language missing

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#21]
on the download page, users can select language based on region. however, the webpage listed every language in Chinese language-family except for Cantonese, which is widely used in China and Hong Kong.

Moved from googlei18n/noto-fonts#173

**Comment by marekjez86** [comment]
@jamesgk : I looked at http://www.google.com/get/noto/#sans-hant Cantonese appears to be listed. Is this correct now?

**Comment by jamesgk** [comment]
Yea, as far as I can tell this is no longer an issue -- it was probably fixed in a major site overhaul. Closing.
