### ISSUE TITLE
missing "is" in website text

### ISSUE THREAD

**Issue by annag42** [googlei18n/nototools#212]
Please make the following substitution:

s/Noto has multiple styles and weights, and freely available to all./Noto has multiple styles and weights, and is freely available to all./g

That is, please add the word "is" for clarity.

This should be done so as to take effect at the following link:
https://www.google.com/get/noto/

I would make a pull request, but I'm not sure a) how to do all the requisite work, and b) that it's necessary for so simple a correction.

Thank you,
annag

**Comment by marekjez86** [comment]
Thank you for the feedback. We'll change it when we have a chance to update it (it is on the main Google's site therefore it may take a while).

**Comment by dougfelt** [comment]
I filed a bug on this.

**Comment by marekjez86** [comment]
Since @dougfelt filed a new bug (I assume internal to Google), I will close this one.

**Comment by jungshik** [comment]
Keep it open for tracking until it's fixed.

**Comment by marekjez86** [comment]
Thanks.

On Fri, Mar 25, 2016 at 1:49 PM, jungshik <notifications@github.com> wrote:

> Keep it open for tracking until it's fixed.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/googlei18n/nototools/issues/212#issuecomment-201493684>
>



-- 

Marek Z Jeziorek [ 老马 ] | marekj@google.com | 312 725-6958

**Comment by Artoria2e5** [comment]
Looks like fixed.
