### ISSUE TITLE
Noto CMAP requirements for Thaana?

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/nototools#246]
In the specifications for the noto_cmap_reqs.py def _assign_complex_scripts_extra, Thaa (Thaana) is not among the scripts listed for assignment to HarfBuzz and the USE. Is this intentional?

**Comment by dougfelt** [comment]
The list was based on the scripts listed on https://www.microsoft.com/typography/OpenTypeDev/USE/intro.htm (which you referenced I think in February) and on the scripts in Harfbuzz in hb-ot-shape-complex-private.hh.  I did not see Thaana listed here, perhaps I missed it, or it should be listed and isn't.  At any rate if there are characters that interact with Thaana whose glyphs need to be in the font, for either USE or some other shaping engine, it would be good to know.

**Comment by behdad** [comment]
This is intentional.
