### ISSUE TITLE
notodiff: on Mac I only get one file generated for a pair of upper case letters

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#269]
My Mac has the following file system:
   File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)

It appears that notodiff generates file names based on the names in the font file. This causes problem when a file system is NOT case sensitive (like my mac).

Current situation:
z.png has the upper case Z (and there's no Z.png)
![z](https://cloud.githubusercontent.com/assets/13322623/17202524/a3eaf6c0-5491-11e6-9a8f-2d2ffce1747e.png)
U.png has the lower case u (and there's no u.png)
![u](https://cloud.githubusercontent.com/assets/13322623/17202537/c00156e2-5491-11e6-8da9-a540657c74dd.png)

Might be better if we append a dash or underscore (one of them works better in one of the file systems, but I could be wrong) followed by a Unicode codepoint. This way we'd get unique file names.

**Comment by jamesgk** [comment]
Not all glyphs will have a unicode codepoint. I suggest adding an underscore to the name after any uppercase letter or underscore (this is similar to what other font programs do).

**Comment by behdad** [comment]
Yeah please make sure you use the same naming as UFO-3.

**Comment by jamesgk** [comment]
> Yeah please make sure you use the same naming as UFO-3.

Is that really important? The UFO3 naming scheme is a lot more complicated than just adding underscores after some characters and I think it's overkill for this application (just naming PNGs that show rendering differences).

**Comment by behdad** [comment]
> Yeah please make sure you use the same naming as UFO-3.
> 
> Is that really important?

No, but I figured if it's the same problem (converting glyphnames to portable filenames), then reuse might make sense.  But we don't have to support dos or anything, so your choice.
