### ISSUE TITLE
curious about this diff

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#277]
when I compare two symbol fonts https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-glyphsapp/unhinted/NotoSansSymbols2-Regular.ttf (as before) and https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/NotoSansSymbols2-Regular.ttf the differences appear to be consistently shifted (see two examples below)
Why are they shifted hence different? What would cause it?

![uni270c_](https://cloud.githubusercontent.com/assets/13322623/17817340/e3239b36-65f2-11e6-8902-39546deaa440.png)
![uni270d_](https://cloud.githubusercontent.com/assets/13322623/17817341/e323ea3c-65f2-11e6-8c4f-d9b81c5da2b2.png)

**Comment by jamesgk** [comment]
I'm pretty sure this would be caused by a change in vertical metrics.
