### ISSUE TITLE
Emoji Colors > flags > view more emoji > error 400

### ISSUE THREAD

**Issue by AqeelAT** [googlei18n/nototools#282]
When clicking on view more emoji under flags in emoji colors it takes you to https://www.google.com/get/noto/help/emoji/flags.html which results in error 404.

**Comment by marekjez86** [comment]
@AqeelAT : please file a bug in https://github.com/googlei18n/noto-emoji/issues if if this is still a problem

**Comment by dougfelt** [comment]
Verified that it is a problem.
