### ISSUE TITLE
Wave SVG flags

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#3]
We want to explore options for generating waved flag SVGs. Detailed discussion can be found in the original thread.

Moved from googlei18n/noto-fonts#358

**Comment by jamesgk** [comment]
cc @behdad @roozbehp @dougfelt @jamesgk @raphlinus

**Comment by behdad** [comment]
Actually, belongs to noto-emoji.  Moved to https://github.com/googlei18n/noto-emoji/issues/3
