### ISSUE TITLE
questions: re name/family and name/full_name ?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#313]
Why do we abbreviate in these names?
Why do we abbreviate inconsistently (see "expecting '[...] SmBd'" and "expecting '[...] SemBd'")?
Who should fix it (IMHO, pipeline generates the file names then the pipeline should provide this info, but I'm a novice in this space)?

E <name/family> The family is 'Noto Sans Devanagari Condensed Light' but was expecting 'Noto Sans Devanagari Cn Lt'
E <name/family> The family is 'Noto Sans Devanagari Condensed Semi' but was expecting 'Noto Sans Devanagari Cn SmBd'
E <name/family> The family is 'Noto Sans Devanagari Condensed' but was expecting 'Noto Sans Devanagari Cn'
E <name/family> The family is 'Noto Sans Sinhala Semi' but was expecting 'Noto Sans Sinhala SemBd'

E <name/full_name> The full name is 'Noto Sans Devanagari Condensed Semi' but was expecting 'Noto Sans Devanagari Condensed SemiBold'
E <name/full_name> The full name is 'Noto Sans Devanagari' but was expecting 'Noto Sans Devanagari Regular'
E <name/full_name> The full name is 'Noto Sans Sinhala Semi' but was expecting 'Noto Sans Sinhala SemiBold'

**Comment by dougfelt** [comment]
There's a legacy limit from the 80's on the length of the names. Most
software doesn't care any more, but you don't know who might still run
something that does care.

**Comment by marekjez86** [comment]
Does it mean we should ignore or correct? If correct, is it a pipeline issue (and if yes, I'll file a bug)?

**Comment by dougfelt** [comment]
The names I have are the names I believe are correct, if we expect to
confirm to the name length limits.

**Comment by marekjez86** [comment]
Duplicate of https://github.com/googlei18n/fontmake/issues/209
