### ISSUE TITLE
notodiff: png image is not wide enough

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#315]
I'm not sure how we decide on how wide the diffed image should be.
Here's the input (left --before; right --after)
![before-after](https://cloud.githubusercontent.com/assets/13322623/20269502/33cc6656-aa38-11e6-9ea3-6a54bc352c93.jpg)

the diff image is missing significant information (IMHO)
![jv__d_dha__pas](https://cloud.githubusercontent.com/assets/13322623/20269524/4c13ae18-aa38-11e6-98b6-dd9793aeead0.png)

**Comment by jamesgk** [comment]
What font is this?

**Comment by marekjez86** [comment]
This was from diff of 
--before https://github.com/googlei18n/noto-fonts/blob/master/alpha/from-pipeline/NotoSansJavanese-Regular.ttf
and
--after (look for submission in https://github.com/googlei18n/noto-fonts/pull/792 )

**Comment by jamesgk** [comment]
Which glyph's image did you attach? I don't see any notodiff output quite like that.

**Comment by marekjez86** [comment]
--before [NotoSansJavanese-Regular.ttf.zip](https://github.com/googlei18n/nototools/files/596529/NotoSansJavanese-Regular.ttf.zip)
--after [NotoSansJavanese-Regular-c.ttf.zip](https://github.com/googlei18n/nototools/files/596530/NotoSansJavanese-Regular-c.ttf.zip)

look for jv__d_dha__pas

**Comment by jamesgk** [comment]
Huh, when I run notodiff on those two fonts I get
` Mark class mismatch for jv_Ddha_pas (no class vs mark)`
and no jv__d_dha__pas.png is generated.

I should have a fix soon for rendering widths anyways, but it's strange that we'd see different things here.
