### ISSUE TITLE
Typo on the FAQ Page

### ISSUE THREAD

**Issue by grub-basket** [googlei18n/nototools#318]
![image](https://cloud.githubusercontent.com/assets/12993901/20460725/2a866b8c-aea2-11e6-9335-f75f6cf5377d.png)

`It's` should be `its`.  

I might be wrong though, as I am interpreting it as though the expert know enough about the (provided) language's typography. 

Here is the [FAQ Page](https://www.google.com/get/noto/help/faq/).

**Comment by dougfelt** [comment]
Thanks for pointing this out.

**Comment by marekjez86** [comment]
I fixed https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md (which is a proto for the referenced here FAQ page).
