### ISSUE TITLE
cannot run noto_lint.py if nototools are setup with "python setup.py install ;"

### ISSUE THREAD

**Issue by xiangyexiao** [googlei18n/nototools#332]
python noto_lint.py ~/fonts4android/NotoSansCherokee-Regular.ttf failed if I setup nototools with:

python setup.py install ;

error message I got is:

# Homedir has no .notoconfig file, see nototools/nototools/notoconfig.py
unknown hint status for /Users/xiangye/fonts4android, defaulting to unhinted
Traceback (most recent call last):
  File "noto_lint.py", line 2079, in <module>
    main()
  File "noto_lint.py", line 2046, in main
    arguments.phase)
  File "noto_lint.py", line 1876, in check_font
    check_name_table()
  File "noto_lint.py", line 640, in check_name_table
    noto_phase)
  File "/usr/local/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/noto_names.py", line 697, in family_to_name_info_for_phase
    path.join(tooldir, _PHASE_TO_FILENAME[phase]))
  File "/usr/local/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/noto_names.py", line 704, in read_family_name_info_file
    return _read_tree(ET.parse(filename).getroot())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/nototools-0.0.1-py2.7.egg/nototools/family_name_info_p3.xml'

Note that, I can run noto_lint with this command:
sudo python setup.py develop

I have done these two steps before setup. 
brew install cairo pango pygtk imagemagick ;
sudo pip install -r requirements.txt ;

My laptop is Mac OSX 10.11.6

**Comment by dougfelt** [comment]
Setup 'install' isn't copying all the data files the various nototools might need.  Using 'develop' doesn't copy them but just uses the directory where the repo is, so finesses this.  Setup.py should be fixed, but it will continue to break as new data files get added because it's easy to forget.  Using 'develop' also means you don't have to rerun setup after you refresh your repo, which is another reason I prefer it.

**Comment by jamesgk** [comment]
The readme instructions use `python setup.py install`, maybe we should change it to develop?

**Comment by dougfelt** [comment]
Also, @xiangye, if you have noto repos, setting up a .notoconfig file can help make the tools more usable.

Create a text file named '.notoconfig' (leading dot) in your home directory, containing the following (replace the text in angle brackets with the corresponding absolute path on your machine):
----- .notoconfig -----
noto_tools=<absolute path to the directory containing your local copy of the nototools repo>
noto_fonts=<... noto_fonts repo>
noto_cjk=<... noto_cjk repo>
noto_emoji=<... noto_emoji repo>
noto_source=<... noto_source repo>

**Comment by xiangyexiao** [comment]
Thanks, Doug. I will try .notoconfig.

Also want the instructions in readme.md to be updated as @jamesgk mentioned.

**Comment by dougfelt** [comment]
Updated the readme instructions.
