### ISSUE TITLE
noto_lint.py: cannot parse anything with "ExtraLight" in a file name [a conjecture based on the sample data below]

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#334]
The pipeline produces files with such a name. We should be able to lint them also.

**Comment by dougfelt** [comment]
So, currently we expect the name 'Thin' to be given to fonts with a weight of 250, because weights under 200 confuse some versions of windows.  And the old noto never had ExtraLight.

'ExtraLight' would normally be 200, and Thin would normally be 100.  ExtraLight should at least have a higher weight than Thin.

@jungshik, what should these names imply in terms of the  weight values?

**Comment by dougfelt** [comment]
@marekjez86 please provide a list of all the various weight names we expect to be dealing with.

**Comment by marekjez86** [comment]
Pipeline generates the following names:

Noto*-Black.ttf
Noto*-BlackItalic.ttf
Noto*-Bold.ttf
Noto*-BoldItalic.ttf
Noto*-Condensed.ttf
Noto*-CondensedBlack.ttf
Noto*-CondensedBlackItalic.ttf
Noto*-CondensedBold.ttf
Noto*-CondensedBoldItalic.ttf
Noto*-CondensedExtraBold.ttf
Noto*-CondensedExtraBoldItalic.ttf
Noto*-CondensedExtraLight.ttf
Noto*-CondensedExtraLightItalic.ttf
Noto*-CondensedItalic.ttf
Noto*-CondensedLight.ttf
Noto*-CondensedLightItalic.ttf
Noto*-CondensedMedium.ttf
Noto*-CondensedMediumItalic.ttf
Noto*-CondensedSemiBold.ttf
Noto*-CondensedSemiBoldItalic.ttf
Noto*-CondensedThin.ttf
Noto*-CondensedThinItalic.ttf
Noto*-ExtraBold.ttf
Noto*-ExtraBoldItalic.ttf
Noto*-ExtraCondensed.ttf
Noto*-ExtraCondensedBlack.ttf
Noto*-ExtraCondensedBlackItalic.ttf
Noto*-ExtraCondensedBold.ttf
Noto*-ExtraCondensedBoldItalic.ttf
Noto*-ExtraCondensedExtraBold.ttf
Noto*-ExtraCondensedExtraBoldItalic.ttf
Noto*-ExtraCondensedExtraLight.ttf
Noto*-ExtraCondensedExtraLightItalic.ttf
Noto*-ExtraCondensedItalic.ttf
Noto*-ExtraCondensedLight.ttf
Noto*-ExtraCondensedLightItalic.ttf
Noto*-ExtraCondensedMedium.ttf
Noto*-ExtraCondensedMediumItalic.ttf
Noto*-ExtraCondensedSemiBold.ttf
Noto*-ExtraCondensedSemiBoldItalic.ttf
Noto*-ExtraCondensedThin.ttf
Noto*-ExtraCondensedThinItalic.ttf
Noto*-ExtraLight.ttf
Noto*-ExtraLightItalic.ttf
Noto*-Italic.ttf
Noto*-Light.ttf
Noto*-LightItalic.ttf
Noto*-Medium.ttf
Noto*-MediumItalic.ttf
Noto*-Regular.ttf
Noto*-SemiBold.ttf
Noto*-SemiBoldItalic.ttf
Noto*-SemiCondensed.ttf
Noto*-SemiCondensedBlack.ttf
Noto*-SemiCondensedBlackItalic.ttf
Noto*-SemiCondensedBold.ttf
Noto*-SemiCondensedBoldItalic.ttf
Noto*-SemiCondensedExtraBold.ttf
Noto*-SemiCondensedExtraBoldItalic.ttf
Noto*-SemiCondensedExtraLight.ttf
Noto*-SemiCondensedExtraLightItalic.ttf
Noto*-SemiCondensedItalic.ttf
Noto*-SemiCondensedLight.ttf
Noto*-SemiCondensedLightItalic.ttf
Noto*-SemiCondensedMedium.ttf
Noto*-SemiCondensedMediumItalic.ttf
Noto*-SemiCondensedSemiBold.ttf
Noto*-SemiCondensedSemiBoldItalic.ttf
Noto*-SemiCondensedThin.ttf
Noto*-SemiCondensedThinItalic.ttf
Noto*-Thin.ttf
Noto*-ThinItalic.ttf

**Comment by jungshik** [comment]
I really hate using '250' for Thin. That's for Windows applications using GDI. If we continue to use that, we may have to use 275 (or something between 250 and 300) for weigh=ExtraLight. 

Alternatively, we can ignore the above Windows-GDI issue and just use 100 for Thin and 200 for EL. 

Yet another alternative is to generate '-Win.ttf' variants for weight=100 and weight=200 with OS2 weight values set to 250 and 275 while using '100' and '200' for non-Windows. 

It's all up to how much we care about Windows GDI applications that use locally installed fonts. 

It does not matter for web font use cases (even on Windows).

**Comment by jungshik** [comment]
BTW, fontconfig on Google's internal Linux is too old to cope with 250 and 275, but a recent (newer than 2014) version of fontconfig can deal with 250 and 275.  Needless to say, even old fontconfig does not have any issue with 100 and 200.

**Comment by dougfelt** [comment]
@marekjez86 
> Pipeline generates the following font file names:
Now, and in the future?  

So, lint wants to know the numeric values to assign to each of these names.

For variable fonts, I expect calling 'Thin' 200 and 'ExtraLight' 250 is going to mess things up.

I'm sort of with Jungshik and think if people want to use fonts on windows with gdi we should just provide them special fonts for that, rather than forcing everything else to deal with the constraints on the weight naming it imposes.

**Comment by jungshik** [comment]
Let's do the most 'rational' thing disregarding the Windows-GDI issue. If Windows users complain, we can add a post-build-hook to generate 'foobar-Win.ttf' variants for Thin and EL.

**Comment by dougfelt** [comment]
@davelab6 do you want to weigh in on this?
