### ISSUE TITLE
noto_lint.py:  Please modify noto_lint.py to handle omitted "Regular" in full name

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#337]
noto_lint.py expects for the full name 'Regular' to be present when there are regular weights, but the noto fonts all omit it. Please modify noto_lint.py to deal with omitted "Regular"

**Comment by dougfelt** [comment]
Yeah, so, in phase 2 MTI omitted 'Regular' in both the full name and the postscript name, and Adobe included 'Regular' in both the full name and the postscript name.

Now the files omit 'Regular from the full name but include it in the postscript name.

@jamesgk, is this something in the sources from Monotype or something our toolchain does?

**Comment by dougfelt** [comment]
FYI, the Glyphs-generated fonts include 'Regular' in both the full name and the postscript name.  Which is what lint had been expecting.  So it looks like the toolchain generates names differently than Glyphs.

**Comment by jamesgk** [comment]
We haven't been including Regular in full names since this change to ufo2ft about a year ago:
https://github.com/googlei18n/ufo2ft/commit/0a7992919fc69661ef3c8941728e5642d9dfac34.

I don't really have a preference but I do generally trust Cosimo et al. to encode font designers' expectations into our tools.

**Comment by dougfelt** [comment]
Yeah.  The thing is, 1) Adobe and MTI do it differently, and 2) our Glyphs-generated files differ in the naming from the tool-generated files.

The last I remember hearing from Behdad, he thought the glyphs sources should be changed where possible in preference to 'fixing' things in the toolchain.  This of course can be cumbersome in the case of a project like noto, where you want the ability to ensure consistent behavior across dozens of source files / hundreds of font instances.  Perhaps it is more straightforward now to apply automated edits across the glyphs sources?

**Comment by jamesgk** [comment]
Actually, I don't think there is a way to force fontmake (or ufo2ft specifically) to include Regular in full names, no matter what we do to the source. If we really want this we might have to either change the default behavior of ufo2ft or make it configurable somehow.
