### ISSUE TITLE
NotoSansArabic: license ends with a CR or LF or CRLF and it fails the noto_lint.py test. Should it?

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#349]
I can tell Monotype to check for this. I can fix it myself, but I wanted to see if this is something that can be handled within noto_lint.py. An advice is appreciated.

E <name/license> The license is 'This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on 
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language,
 permissions and limitations governing your use of this Font Software.
' but was expecting 'This Font Software is licensed under the SIL Open Font License, Version 1.1. This Font Software is distributed on an "AS IS" B
ASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the SIL Open Font License for the specific language, permissions
 and limitations governing your use of this Font Software.'

**Comment by dougfelt** [comment]
I think lint is right to point this out.  Generally we don't have CR/LF at the end of any of these.  Whether Monotype fixes it or we fix it in the sources ourselves doesn't really matter.

**Comment by marekjez86** [comment]
Thank you. I'll require MTI to conform to this spec.
