### ISSUE TITLE
noto_lint.py: should take into consideration "units per Em" when considering ascent and descent in hhea table

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#355]
For example, "units per Em" in NotoSansSinhala-SemiCondensedExtraLight is 1000.
![notosanssinhala-semicondensedextralight](https://cloud.githubusercontent.com/assets/13322623/21455437/d09fceb8-c8d4-11e6-9de3-afbb2ffe25b8.jpeg)

However, noto_lint.py reports the following for NotoSansSinhala-SemiCondensedExtraLight
_E <head/hhea/ascent> Value of ascent in 'hhea' table is 1011, but should be 2189.
E <head/hhea/descent> Value of descent in 'hhea' table is -293, but should be -600._

The numbers required by noto_lint.py are correct for "units per Em" of 2048, but are 2.048 too large for "units per Em" of 1000

Hence, noto_lint.py should take into consideration "units per Em" when considering ascent and descent values in 'hhea' table.

Are there any other numbers that should also adjust in noto_lint.py based on "units per Em"  value?

**Comment by dougfelt** [comment]
Yep. You can assign this to me.

**Comment by marekjez86** [comment]
Another instance of this happened for Noto Sans Ogham script ( https://github.com/googlei18n/noto-source/blob/master/src/NotoSansOgham-MM.glyphs ) when using both Glyphs.app and the pipeline to fonts from this source:

_E <stem/right_joining> The glyph for U+1680 (OGHAM SPACE MARK) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1681 (OGHAM LETTER BEITH) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1682 (OGHAM LETTER LUIS) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1683 (OGHAM LETTER FEARN) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1684 (OGHAM LETTER SAIL) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1685 (OGHAM LETTER NION) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1686 (OGHAM LETTER UATH) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1687 (OGHAM LETTER DAIR) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1688 (OGHAM LETTER TINNE) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1689 (OGHAM LETTER COLL) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+168A (OGHAM LETTER CEIRT) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+168B (OGHAM LETTER MUIN) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+168C (OGHAM LETTER GORT) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+168D (OGHAM LETTER NGEADAL) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+168E (OGHAM LETTER STRAIF) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+168F (OGHAM LETTER RUIS) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1690 (OGHAM LETTER AILM) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1691 (OGHAM LETTER ONN) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1692 (OGHAM LETTER UR) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1693 (OGHAM LETTER EADHADH) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1694 (OGHAM LETTER IODHADH) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1695 (OGHAM LETTER EABHADH) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1696 (OGHAM LETTER OR) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1697 (OGHAM LETTER UILLEANN) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1698 (OGHAM LETTER IFIN) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+1699 (OGHAM LETTER EAMHANCHOLL) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+169A (OGHAM LETTER PEITH) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70.
E <stem/right_joining> The glyph for U+169B (OGHAM FEATHER MARK) is supposed to have a stem connecting to the right, but it's right side bearing is -34 instead of -70._

**Comment by jungshik** [comment]
Wans't this fixed a while ago?

**Comment by dougfelt** [comment]
Yes.
