### ISSUE TITLE
Need a tool to calculate the bounding box (vertical) of a "shaped/positioned" string

### ISSUE THREAD

**Issue by jungshik** [googlei18n/nototools#369]
For a UI font, it's important for the result of OT-shaping stays within a given vertical bounding box. Otherwise, glyphs would be clipped or go out of the box. 

We need a tool to calculate the vertical bounding box for a given input string shaped with a given font. 

A couple of possibilities came up. 

1) Process the JSON output  with --show-extents and --output-format=json options to calculate the vertical bounding box

2) Write a separate program using HB to calculate the vertical bounding box.  

@dougfelt @KatMomoi @iverg @behdad @roozbehp 

Eventually, this can be integrated into Noto Lint.

**Comment by behdad** [comment]
I'm fairly sure Roozbeh already wrote code in nototools for this.  Why a commandline tool?  Why not Python code?

**Comment by behdad** [comment]
Or maybe it was in Roboto?

**Comment by roozbehp** [comment]
It's in nototools. Look for the render.py module and the scripts that call it.

**Comment by jungshik** [comment]
Thanks !
I vaguely remembered that Roozbeh had written that and ran the calculation over strings extracted from our translation repos.
