### ISSUE TITLE
[Question] Where is hb-view?

### ISSUE THREAD

**Issue by miguelsousa** [googlei18n/nototools#397]
When I install the dependencies thru brew I get **harfbuzz v1.4.5** and the bin folder contains only the tools `hb-ot-shape-closure` and `hb-shape`.

When I try to run **notodiff** with the *rendered* option it fails because it cannot find `hb-view`.

What am I missing?

**Comment by zjusbo** [comment]
Probably you need to run this command if you are using linux.
sudo apt-get install libharfbuzz-bin

I have no idea either why we do not install libharfbuzz-bin automatically with the notodiff.
Reference:
https://github.com/googlei18n/nototools/issues/392

**Comment by khaledhosny** [comment]
You need to build HarfBuzz with Cairo support enabled (`--with-cairo`) to get `hb-view`, by default Homebrew builds without Cairo.

**Comment by miguelsousa** [comment]
Thanks Khaled. Do you have a suggestion on how to modify the installation instructions? As they stand they're incomplete.

**Comment by khaledhosny** [comment]
I can’t test on Mac right now, but I think something like this should work (you might also need to uninstall harfbuzz first or force reinstall, I don’t remember exactly how):

    brew install --with-cairo harfbuzz cairo pango pygtk imagemagick

**Comment by miguelsousa** [comment]
I confirmed that that works. Thanks Khaled.
I've submitted a patch in this PR https://github.com/googlei18n/nototools/pull/395
