### ISSUE TITLE
In create_image.py, make sure only Noto fonts are used

### ISSUE THREAD

**Issue by jamesgk** [googlei18n/nototools#4]
Right now, if a character doesn't exist in the main Noto font, there's a chance it will fallback to another font rather than Noto fonts. Make sure only Noto will be used in the fallback chain.

Moved from googlei18n/noto-fonts#66

**Comment by jamesgk** [comment]
cc @behdad @roozbehp

**Comment by behdad** [comment]
This was actually fixed a while ago.
