### ISSUE TITLE
Referenced domain unhchr.ch/udhr is up for sale, must be changed

### ISSUE THREAD

**Issue by ng-0** [googlei18n/nototools#451]
In the directory third_party, http://www.unhchr.ch/udhr is being used as an URL. However this domain
at the time I'm writing this is "for sale".

Was this your work, or did you get the files from upstream (UN / OHCHR)?

**Comment by ng-0** [comment]
You should probably be referencing http://www.ohchr.org/EN/UDHR/Pages/Introduction.aspx for its section:
```
 Permissions:

If UDHR translations or materials are reproduced, users should make reference to this website as a source by providing a link. All suggestions or modifications concerning translations posted on this website can be sent to hredatabase@ohchr.org. 
```

But IANAL.

**Comment by dougfelt** [comment]
This is upstream data from unicode.org/udhr.  Best to file a bug with them, we don't change these files.

**Comment by eric-muller** [comment]
See <https://github.com/unicode-org/udhr/issues/15>.
