### ISSUE TITLE
build instructions - setuptools install error + workaround 

### ISSUE THREAD

**Issue by eladkarako** [googlei18n/nototools#464]
<code>pip install -r requirements.txt</code>
will report this error while trying to install setuptools:
<em><code>Could not import setuptools which is required to install from a source distribution. Please install setuptools.</code></em>:
<img src="https://i.imgur.com/gWYO6fK.png"/>

I've installed it separately using <code>sudo pip install -U setuptools</code>
and followed with <code>pip install -r requirements.txt</code> again:

<img src="https://i.imgur.com/GV2d84V.png"/>

got it from here:
<a href="https://github.com/fredley/play-pi/issues/22#issuecomment-189767362">https://github.com/fredley/play-pi/issues/22#issuecomment-189767362</a>

<hr/>
edit:
It appears that pip version 8.1.1 (which is what current apt-get will get you on Linux Ubuntu/Mint) does not have this issue, or that it wasn't appeared for some reason...
in this vm-installation, I did upgrade to latest version (9.0.1, using <code>pip install --upgrade pip</code>) and then executed <code>pip install -r requirements.txt</code> with the latest version, but in my previous installation I ran <code>pip install -r requirements.txt</code> with version 8.1.1 which seems to pass without any issues...

just FYI..

**Comment by anthrotype** [comment]
Glad you were able work around the issue.
Closing since it’s not specific to nototools.
