### ISSUE TITLE
Are noto TTF files rendering specific unicode ranges, and if yes, is there a map?

### ISSUE THREAD

**Issue by jokoon** [googlei18n/nototools#469]
Hello,

First thanks for releasing those awewsome free fonts!

I have this little project to display all fonts in a webpage, obviously my system doesn't have all fonts.

I'm using unicode ranges from the Blocks.txt from the unicode.org website.

Is there somewhere data that describes which codepoint range of unicode are rendered by which noto TTF font file?

Regards,
Jonas

**Comment by dougfelt** [comment]
Unfortunately, we don't have such a data file.

We're in the middle of a transition for the fonts so there is no document currently describing the exact coverage of each font.  The only such files are the planning files, for example the planned coverage for phase 3 (we're about 3/4 finished with that) is in data/noto_cmap_phase3.xml.

We don't cover strictly by blocks, though most fonts generally line up with the script-specific blocks that you'd expect.  Notable exceptions, for example, are LGC and Symbols, which cover multiple blocks and ranges.

There are tools that you can use to generate coverage information, though you'd then have to parse that output to figure it out.  generate_coverage_data.py will take files and/or directories and examine the fonts there, building a 'coverage' xml file that shows for each font the ranges of codepoints it covers.  noto_font_coverage.py writes information that is organized in the opposite fashion, mapping from codepoints to the fonts that cover them.  It however looks only at the noto fonts at their locations in your local noto repos.  coverage.py takes a list of fonts and writes the cmap of each font in a number of different formats that you can select from.

All of these tools require that you have nototools set up and installed, with the accompanying additional tools.  There are docker files that help automate this process.

Fundamentally all these tools use fontTools to open the file and extract the cmap.  If you have ttx installed you can use it to dump cmaps of individual fonts and do what you want with that information.
