### ISSUE TITLE
Export individual glyphs as SVG?

### ISSUE THREAD

**Issue by ebraminio** [googlei18n/nototools#57]
For some FOSS related application I like to have each glyph of a particular Noto font extracted as well formed SVG files possibly with project preferred meaningful file names. Maybe this tools can have or already has this functionality? Thank you

**Comment by davelab6** [comment]
FontForge (via python scripting) can probably do this

**Comment by ebraminio** [comment]
Thank you. I should have note that, I am using fontforge gui for this currently but have to editthe result manually on Inkscape to edit glyph boundraies afterward. Maybe something using fontforge scripting but specialized to work correctly with noto font would be nice. I've also prepared a C++ that is doing this using freetype and have correct SVG boundraies but prefer if there would be some semi-official way for noto to extract glyphs with the project preferred preference and naming style.

**Comment by behdad** [comment]
Using fonttools and the draw() method of ttFont.getGlyphSet()[*] also should be rather straightforward.

**Comment by dougfelt** [comment]
I'm going to close this since it's unlikely that we'll do this ourselves anytime soon.
