### ISSUE TITLE
Verify presence of single glyphs for Unicode Named Sequences

### ISSUE THREAD

**Issue by brawer** [googlei18n/nototools#59]
Could/should the noto lint tool verify that there is a single glyph for each of the “named sequences” in the Unicode data files? For example, U+0DCA U+200D U+0DBB for Sinhala Consonant Sign Rakaaraansaya.

Here’s the corresponding file for Unicode 7.0:
http://www.unicode.org/utility/trac/browser/trunk/unicodetools/data/ucd/7.0.0-Update/NamedSequences.txt?rev=head

**Comment by roozbehp** [comment]
The actual latest data files are at http://www.unicode.org/Public/UCD/latest/ucd/NamedSequences.txt and http://www.unicode.org/Public/UCD/latest/ucd/NamedSequencesProv.txt

**Comment by brawer** [comment]
@dougfelt, what do you think?

**Comment by dougfelt** [comment]
Sure. I expect lint would just ask harfbuzz to generate glyphs for the
sequence and verify that there is only one (where the font supports all the
original characters).

**Comment by jungshik** [comment]
I'm a bit confused about this issue. Should there be a single glyph for a character sequence just because it is listed in NamedSequences.txt?  For instance, can "LATIN CAPITAL LETTER A WITH MACRON AND GRAVE" be made of three glyphs whose positions are controlled by GPOS? 

Or, I must be missing something obvious.

**Comment by roozbehp** [comment]
I'm with @jungshik here. Looking at the list, most of it doesn't need to be a single glyph. Some of the Indic ones do, but those could be handled using a better (and more comprehensive mechanism).

**Comment by brawer** [comment]
OK, closing.
