### ISSUE TITLE
Tai Le: Combining diacritics are missing from the font

### ISSUE THREAD

**Issue by marekjez86** [googlei18n/nototools#62]
moved from https://github.com/googlei18n/noto-alpha/issues/243

Imported from [Google Code issue #243](https://code.google.com/p/noto-alpha/issues/detail?id=243) created by [roozbeh@google.com](https://code.google.com/u/roozbeh@google.com/) on 2014-06-14T01:33:00.000Z:

----
The traditional Tai Le orthography uses the following five combining characters as tone marks, but they are missing from the Noto Sans Tai Le font: U+0300, U+0301, U+0307, U+0308, and U+030C.

GPOS and GSUB information should also be added to the font to position the characters properly. Also note that the Unicode standard specifies that &quot;When one of the combining diacritics follows a tall letter [...], it is displayed to the right of the letter, [...]&quot; basically becoming spacing.

See http://www.unicode.org/L2/L2001/01369-n2372.pdf and section 11.5 of Unicode Standard version 6.2 (http://www.unicode.org/versions/Unicode6.2.0/ch11.pdf).

**Comment by jungshik** [comment]
googlei18n/noto-fonts#472 deals with fixing the font. This is about adding a check to lint tool.

**Comment by dougfelt** [comment]
noto_lint already flags these missing characters as an error in TaiLe.

It did not flag the lack of GPOS/GSUB as a separate error, however, because Tai Le was whitelisted as not needing it.  I removed that in commit 74062055.
