### ISSUE TITLE
Modify lint tool to add 'informative' warnings separate from errors

### ISSUE THREAD

**Issue by dougfelt** [googlei18n/nototools#68]
Also, change the lint tool to report mismatches of general category / glyph class (for marks) as warnings instead of errors.  See excerpt from email thread below.

>>We are often in a quandry when matching the Unicode sub-classification
of marks to OpenType classes.

>I'd argue that there is no requirement to match them, since they serve different purposes. The classification of mark in GDEF is something that enables particular kinds of glyph-level operations that have nothing to do with character level classification

> I suggest either removing this from the Lint testing or identifying such reports as informative rather than as errors.

**Comment by davelab6** [comment]
Nice!

**Comment by dougfelt** [comment]
I implemented this in commit ef4d5a00.
