### ISSUE TITLE
Noto Lint Tool - Way to Control Reporting of Issues

### ISSUE THREAD

**Issue by oliviazhu** [googlei18n/nototools#7]
The tool noto_lint.py should have a system to control the reporting of issues 
and to not dump spurious errors and warnings.

The linter takes --extrema_threshold, but still prints out warning messages for 
non-zero extrema violations that are under the threshold. But we want the 
linter to be mostly quiet, about warnings. So the linter should suppress these 
messages and simply report that there were N warnings about extrema.

Also, since it appears we're going to accept a lot of these extrema violations, 
we should default the threshold to something like .75 just to get the noise out 
of the system.

All extrema failures are important, because they impact fontcrunch's ability to 
optimize outlines. So the threshold argument isn't all that useful in practice. 
 Instead I'll add an option to suppress extrema error reporting for purposes of 
pruning the lint output. And leave the default to report.

Moved from googlei18n/noto-fonts#276

**Comment by dougfelt** [comment]
Fixed with config.
