### ISSUE TITLE
relationship between different script and language.

### ISSUE THREAD

**Issue by c933103** [googlei18n/nototools#73]
Actually, is it better to post https://github.com/googlei18n/noto-fonts/issues/485 here?

>As on http://www.google.com/get/noto/ , it have stated that language data are taken from Unicode CLDR repository. But how about those languages that do not include in the CLDR? As on the page, it said the following languages use Noto Sans CJK SC:
-Cantonese
-Gan Chinese
-Literary Chinese (Simplified script)
-Min Nan Chinese
-Simplified Chinese
-Wu Chinese
-Xiang Chinese
-Zhuang (Simplified script)
While the following language use Noto Sans CJK TC:
-Hakka Chinese
-Literary Chinese
-Traditional Chinese
Which I believe the CLDR data only include Traditional Chinese and Simplified Chinese data.

>And the reason I am asking about that is that sone data appears to be problematic, as while some people do write Cantonese and Min Nan Chinese in simplified han script, it's more common for me to see those languages written woth traditional han script, and sometime the Min Nan Chinese is also written with latin alphabet via romanization. And while it is not uncommon to see Hakka Chinese in traditional han script, some would write then in simplified han script too. I am not knowledgeable about Wu/Xiang/Zhuang/Gan enough to say are they simplified script only (or simplified+latin only) but you might want to check that do they write in traditional script.

>And for non-han languages, according to Wikipedia, Ainu language also use latin script, and Vietnamese language also use han script.

**Comment by dougfelt** [comment]
Either place works.  I responded in noto-fonts.

**Comment by dougfelt** [comment]
Let's leave the discussion in noto-fonts for now.
