### ISSUE TITLE
UDHR sample in Tswana.

### ISSUE THREAD

**Issue by Kanjilearner817** [googlei18n/nototools#78]
Here's the First Article in Tswana, copied and pasted from Omniglot.
Batho botlhe ba tsetswe ba gololosegile le go lekalekana ka seriti le ditshwanelo. Ba abetswe go akanya le maikutlo, mme ba tshwanetse go direlana ka mowa wa bokaulengwe.

**Comment by brawer** [comment]
This version isn’t good? http://www.unicode.org/udhr/d/udhr_tsn.html

**Comment by marekjez86** [comment]
@Kanjilearner817 : what seems to be an issue here?
